### PR TITLE
fix direction to nonexistent "apply for launch" button

### PR DESCRIPTION
**Pull request by vrooje**
I think this is the only place this is mentioned? @mrniaboc recently pointed out that this button doesn't exist and we should redirect to contact@ instead. I didn't put any code in to hide the email address from spam harvesters.

### CODE REVIEW

**Comment by lcjohnso** [comment]
Looks good to me!

**Comment by vrooje** [comment]
Guessing we should flag someone to review it - @camallen any suggestions?

**Comment by camallen** [comment]
@lcjohnso you should have had merge rights on this repo. I assume you know this but we normally issue a formal PR review and if the issuer is outside the org we merge for them, https://help.github.com/en/articles/about-pull-request-reviews

**Comment by lcjohnso** [comment]
@camallen I was able to merge, but didn't want to overstep (have not been fully briefed on formal process, required testing, etc).  I should talk to you or Sarah in the near future about how I should proceed on this sort of task.  Thanks for bringing this up!

**Comment by camallen** [comment]
Happy to have a chat and tbh the best place might be in a public dev channel on slack for others to engage with.

**Pull request merged**
